# Generated by Django 2.1.2 on 2018-10-31 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('user_id', models.IntegerField()),
                ('password', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=32, null=True)),
                ('sex', models.CharField(max_length=16, null=True)),
                ('birthday', models.CharField(max_length=64, null=True)),
                ('tel', models.CharField(max_length=64, null=True)),
                ('email', models.CharField(max_length=64, null=True)),
                ('address', models.CharField(max_length=64, null=True)),
                ('introduction', models.CharField(max_length=255, null=True)),
                ('token', models.CharField(max_length=255)),
            ],
        ),
    ]
