# Generated by Django 2.1.2 on 2018-11-01 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20181031_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='address',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='birthday',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='introduction',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='sex',
            field=models.CharField(max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='tel',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='token',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='user_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
