# Generated by Django 2.1.2 on 2018-11-10 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [

        migrations.AlterField(
            model_name='datastream',
            name='unit',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='datastream',
            name='unit_symbol',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
