# Generated by Django 2.1.2 on 2018-11-14 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20181114_0143'),
    ]

    operations = [

    ]
