# Generated by Django 2.1.2 on 2018-11-14 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20181114_0144'),
    ]

    operations = [

    ]