# Generated by Django 2.1.2 on 2018-11-01 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20181101_0223'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=32)),
                ('date', models.DateTimeField()),
                ('dev', models.ManyToManyField(to='website.Device')),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='dev',
            field=models.ManyToManyField(to='website.Device'),
        ),
    ]
