# Generated by Django 2.1.2 on 2018-11-18 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20181114_0148'),
    ]

    operations = [

        migrations.AlterField(
            model_name='datastream',
            name='max',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='datastream',
            name='min',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
