# Generated by Django 2.1.2 on 2018-11-01 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20181101_0231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='data',
            name='dev',
        ),
        migrations.AddField(
            model_name='device',
            name='dev_data',
            field=models.ManyToManyField(to='website.Data'),
        ),
    ]
