# Generated by Django 2.1.2 on 2018-11-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_auto_20181101_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='max',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='min',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='weixin_id',
            field=models.CharField(max_length=64, null=True),
        ),
    ]
